/* INSERTS TO THE CLIENT´S AND INSURANCE */


use args01;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ADDINSURANCE`(
in SegurosP varchar(10000),
in SegurosDesP varchar(10000),
in EstautsP INT(1)
)
BEGIN
	INSERT INTO args01.ARGS_SEGUROS( SEGUROS_TYPE, SEGUROS_DESC, ESTATUS) VALUES ( SegurosP, SegurosDesP, EstautsP);
    select CONCAT(A1.CL_NOMBRES, ' ' , A1.CL_APELLIDOS) AS NOMBRE_COMPLETO,
	B1.SEGUROS_TYPE,B1.SEGURO_DESC, A1.CL_CORREO, A1.CL_NUMERO
	from args_clientes A1
	INNER JOIN ARGS_SEGUROS B1 ON B1.IDSEGUROS = A1.IDSEGUROS
	WHERE IDSEGUROS = (SELECT LAST_INSERT_ID());
END$$

/* UPDATE´S */

-- UPDATE SEGUROS -- 
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_INSURANCE`(
 IN `idSegurosP`  INT,
 IN `SegurosP`  varchar(10000),
 IN `SegurosDesP` VARCHAR(10000), 
 IN `EstautsP` INT(1)
 )
BEGIN
	UPDATE ARGS_SEGUROS SET name = SegurosP, status = EstautsP WHERE idSeguros = idSegurosP;
END$$



/* DELETE */

-- DELETE SEGUROS --
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_INSURANCE`(
 IN `idSegurosP`  int
 )
BEGIN
	DELETE FROM ARGS_SEGUROS WHERE idSeguros = idSegurosP;
END$$


-- DELETE CLIENT´S --
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_CLIENT`(
 IN `idClienteP`  int
 )
BEGIN
	DELETE FROM ARGS_CLIENTES WHERE idCliente = idClienteP;
END$$

/* SELECTS */

-- SELECT ONE ENSURANCE --
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SELECT_ONE_ENSURANCE`(
 IN `idSegurosP`  INT
 )
BEGIN
	SELECT SEGUROS_TYPE, SEGUROS_DESC, ESTATUS FROM ARGS_SEGUROS 
    WHERE ESTATUS NOT IN (0);
END$$

-- SELECT MULTIPLE ENSURANCE WITH CLIENTS --
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SELECT_MULTIPLE_ENSURANCE`(
 )
BEGIN
    select CONCAT(A1.CL_NOMBRES, ' ' , A1.CL_APELLIDOS) AS NOMBRE_COMPLETO,
	B1.SEGUROS_TYPE,B1.SEGURO_DESC, A1.CL_CORREO, A1.CL_NUMERO
	from args_clientes A1
	INNER JOIN ARGS_SEGUROS B1 ON B1.IDSEGUROS = A1.IDSEGUROS;
END$$



DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SELECT_SEGUROS`(
 )
BEGIN
	select * from args_seguros
    where estatus not in(0);
END$$





